name: pygraf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - basemap=1.3.0
  - basemap-data-hires=1.2.1
  - pynio=1.5.5
  - matplotlib=3.2.1
  - metpy=0.12.1
  - pylint=2.4.4
  - pytest=5.2.4
  - pyyaml=5.3.1
  - xarray=0.15.1
