name: graphics_tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_graphics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: pygraf
          environment-file: environment.yml
          default_threads: 8
      - run: pylint *.py
      - run: pylint abd_graphics
      - run: pylint tests
      - run: python -m pytest --nat-file tests/data/wrfnat_hrconus_07.grib2 --prs-file tests/data/wrfprs_hrconus_07.grib2
